name: graph_theory
dependencies:
- python>=3.11
- pip
- numpy
- pandas
- matplotlib
- seaborn 
- pip: 
  - git+https://github.com/TieuLongPhan/SynUtils.git
  # - pip install synutility[all]
  # - pip install synutility